### ISSUE TITLE
Cannot use tools with Aftman when Foreman is already managing them

### ISSUE THREAD

**Issue by vocksel** [LPGhatguy/aftman#50]
I have some projects that use Foreman, and when trying to install the same tools via Aftman I run into issues where Foreman is still trying to invoke those tools.

Here's my `aftman.toml`:
```toml
# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
luau-lsp = "JohnnyMorganz/luau-lsp@1.21.0"
rojo = "rojo-rbx/rojo@7.3.0"
selene = "kampfkarren/selene@0.25.0"
stylua = "JohnnyMorganz/StyLua@0.18.0"
wally = "UpliftGames/wally@0.3.2"
```

And after running `aftman install`, attempting to run `wally init` results in the following:
```
➜  camera-shaker git:(wally) wally init
'wally' is not a known Foreman tool, but Foreman was invoked with its name.

To use this tool from /Users/marin/Code/camera-shaker, declare it in a 'foreman.toml' file in the current directory or a parent directory.

Available Tools:

➜  camera-shaker git:(wally) 
```

Is this something that Aftman could provide support for? Or is this ultimately an issue with Foreman that would need to be patched? I'm hoping for the former, because I don't expect Foreman to receive any special support to not conflict with Aftman.
 
I'm currently torn on switching to Aftman because I have several projects still using Foreman, and there will continue to be projects owned by Roblox and other authors that won't be ported to Aftman.
