### ISSUE TITLE
Expanding Beyond Exact Version Dependencies

### ISSUE THREAD

**Issue by nightcycle** [LPGhatguy/aftman#72]
Hello! Really like this tool and I use it a lot, thank you for all the hard work y'all put into it! 

That being said, I've found myself quite missing the update logic I could bake in with Foreman. As stated in the documentation, I am aware this was an intentional decision:

> Exact version dependencies. Using a range here has tripped up lots of users, so Aftman uses exact versions in all configuration files.

I guess I'm here to appeal that on a few points:
- I've no doubt it has tripped people up, it has tripped me up in the past - but so did learning Rojo, once I got through the pain points it allowed me to really level up my development efforts. I feel this is the same situation.
- I think most novice users who aren't as familiar with semantic versioning won't dig much deeper than the front-page documentation. I think if we added support for it and just didn't advertise it, we'd open the door to those developers responsible enough to tackle it, without misleading those just starting out.
- Lacking support for "~" / hotfixes is especially limiting. The other things you could argue are just nice to haves, but if a project has a bad release we want to make it as easy as possible to remedy that. My inbox is filled with release notifications, it's quite possible I mix a patch to a tool I rely on. There is of course the edgecase that I might be relying on a broken behavior, but I don't think we should aim to enable that automatically. If someone needs a broken behavior that is when they would make the decision to lock to a single version.

I don't have the same amount of experience with open source tool development as y'all, but it is my perspective that not supporting beyond exact version dependencies is a hinderance outweighing the accessibility benefits. 

**Problem**
I've found that some of the handiest tools in my toolchain update quite frequently in ways that just make things better without many changes on my part. If I was using a package manager, I'd mark them accordingly and clear the lock file to allow for regular updates. I'd rather build out my testing flow to catch when a change in a tool breaks something, rather than have to manually review every single update.

Currently what I have to do is this:
```toml
[tools]
luau-lsp = "JohnnyMorganz/luau-lsp@1.40.0"
stylua = "JohnnyMorganz/StyLua@2.0.2"
rojo = "rojo-rbx/rojo@7.4.4"
wally = "UpliftGames/wally@0.3.2"
selene = "kampfkarren/selene@0.27.0"
```

What I want to do this is:
```toml
[tools]
luau-lsp = "JohnnyMorganz/luau-lsp@>1.0"
stylua = "JohnnyMorganz/StyLua@^2.0"
rojo = "rojo-rbx/rojo@~7.4.4"
wally = "UpliftGames/wally@>=0.3"
selene = "kampfkarren/selene@<0.28.0"
```

**Proposed Changes**
In prep for writing this post I explored the [tool_id.rs](https://github.com/LPGhatguy/aftman/blob/main/src/tool_id.rs) script, it seems to rely on the semver package which has [native support for these kind of operations](https://docs.rs/semver/latest/semver/enum.Op.html). With changes to the ToolId struct to parse the new string patterns + modifying the get_release function in [tool_source/github.rs](https://github.com/LPGhatguy/aftman/blob/main/src/tool_source/github.rs), I believe we could add this support with minimal friction.

I'm happy to make a pull request attempting this, but before I put in the effort I wanted to bring it up as an issue as it goes pretty explicitly against the "Exact version dependencies" aspect of the original motivation statement.

Thank you for reading!
